services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    # long syntaxで記述
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./node_modules
        target: /app/node_modules
    # ホットリロードの有効化
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    restart: always
    tty: true
    stdin_open: true
# node_modules については、コンテナ内の node_modules を保持するために、volume を用いて永続化
volumes:
  node_modules:
