#
name: nextjs-ci

on:
  # メインブランチにpushがあったときにワークフローを実行
  push:
    branches: [ master ]
  # メインブランチに対するプルリクエストが作成されたときにワークフローを実行
  pull_request:
    branches: [ master ]

jobs:
  nextjs-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 使用するNode.jsのバージョンを定義
        node-version: [18.x]
    steps:
      # 実行環境にソースコードを取り込む
      - uses: actions/checkout@v3
      # 実行環境に対してNode.jsのセットアップをする
      # 作業に任意の名前を定義
      - name: Use Node.js ${{ matrix.node-version }}
        # Node.jsのセットアップに必要な設定
        uses: actions/setup-node@v3
        with:
          # Node.jsのバージョンを指定
          node-version: ${{ matrix.node-version }}
          # yarnのキャッシュを使用する設定
          # cache: 'yarn'
      # 作業に任意の名前を定義
      - name: Install dependencies
      # プロジェクトの依存関係をインストール
        run: npm install
      # 作業に任意の名前を定義
      # - name: Format code
      #   # Prettierでフォーマット
      #   run: yarn prettier
      # 作業に任意の名前を定義
      - name: Lint code
        # ESLintで静的解析の実行
        run: npm run check
