#
name: nextjs-ci test sample

on:
  # メインブランチにpushがあったときにワークフローを実行
  push:

jobs:
  nextjs-ci-test-sample:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 使用するNode.jsのバージョンを定義
        node-version: [18.x]
    steps:
      - name: npm 
        shell: bash
        run: |
          npm install
          npm run test
